"use strict";
// Example sidebar lists for different age groups
var sidebarListsByAge = {
    "0-2": [
        { "icon": "fa-solid fa-calculator", "topic": "All Videos", "searchQuery": "educational videos for toddlers, baby learning videos" },
        { "icon": "fa-solid fa-calculator", "topic": "Numbers", "searchQuery": "learning numbers, counting for toddlers, numbers song" },
        { "icon": "fa-solid fa-book", "topic": "Alphabets", "searchQuery": "learning alphabets, ABC song, alphabet games" },
        { "icon": "fa-solid fa-flask", "topic": "Science", "searchQuery": "basic science for toddlers, fun science experiments, nature for toddlers" },
        { "icon": "fa-solid fa-music", "topic": "Music", "searchQuery": "nursery rhymes, kids songs, baby music videos" },
        { "icon": "fa-solid fa-laptop", "topic": "Animals", "searchQuery": "animal sounds, animal names, animal videos for kids" },
        { "icon": "fa-solid fa-palette", "topic": "Art", "searchQuery": "drawing for toddlers, painting activities, easy crafts for kids" },
        { "icon": "fa-solid fa-scissors", "topic": "Craft", "searchQuery": "easy crafts for toddlers, DIY crafts for kids, paper crafts" },
        { "icon": "fa-solid fa-book-open", "topic": "Story", "searchQuery": "bedtime stories, short stories for toddlers, animated stories" },
        { "icon": "fa-solid fa-film", "topic": "Movie", "searchQuery": "kids movies, animated movies for toddlers, short films for toddlers" },
        { "icon": "fa-solid fa-rocket", "topic": "Space", "searchQuery": "space for toddlers, planets for kids, astronaut videos" },
        { "icon": "fa-solid fa-globe", "topic": "Color", "searchQuery": "learning colors, color songs, color matching activities" },
        { "icon": "fa-solid fa-microphone", "topic": "Phonics", "searchQuery": "phonics for toddlers, letter sounds, phonics songs" },
        { "icon": "fa-solid fa-flag", "topic": "Ye Ethiopia Lijoch", "searchQuery": "Ethiopian kids songs, Ethiopian culture for kids, Amharic kids videos" }
    ],
    "3-4": [
        { "icon": "fa-solid fa-calculator", "topic": "All Videos", "searchQuery": "preschool learning videos, educational videos for kids" },
        { "icon": "fa-solid fa-calculator", "topic": "Numbers", "searchQuery": "counting games, addition for kids, subtraction for kids" },
        { "icon": "fa-solid fa-book", "topic": "Alphabets", "searchQuery": "alphabet writing, ABC tracing, phonics games" },
        { "icon": "fa-solid fa-flask", "topic": "Science", "searchQuery": "science for preschoolers, fun experiments, nature videos for kids" },
        { "icon": "fa-solid fa-music", "topic": "Music", "searchQuery": "kids dance songs, musical instruments for kids, nursery rhymes" },
        { "icon": "fa-solid fa-laptop", "topic": "Animals", "searchQuery": "animal facts for kids, zoo animals, farm animals" },
        { "icon": "fa-solid fa-palette", "topic": "Art", "searchQuery": "drawing for kids, coloring activities, art projects for kids" },
        { "icon": "fa-solid fa-scissors", "topic": "Craft", "searchQuery": "craft ideas for kids, paper folding crafts, creative DIY for kids" },
        { "icon": "fa-solid fa-book-open", "topic": "Story", "searchQuery": "classic kids stories, animated fairy tales, bedtime stories" },
        { "icon": "fa-solid fa-film", "topic": "Movie", "searchQuery": "kids animated movies, short films for preschoolers, educational movies" },
        { "icon": "fa-solid fa-rocket", "topic": "Space", "searchQuery": "solar system for kids, planets videos, space exploration for kids" },
        { "icon": "fa-solid fa-globe", "topic": "Color", "searchQuery": "learning colors, color recognition, color activities for kids" },
        { "icon": "fa-solid fa-microphone", "topic": "Phonics", "searchQuery": "phonics games, vowel sounds, consonant blends" },
        { "icon": "fa-solid fa-flag", "topic": "Ye Ethiopia Lijoch", "searchQuery": "Ethiopian kids videos, Ethiopian history for kids, Ethiopian songs for kids" }
    ],
    "5-7": [
        { "icon": "fa-solid fa-calculator", "topic": "All Videos", "searchQuery": "preschool learning videos, educational videos for kids" },
        { "icon": "fa-solid fa-calculator", "topic": "Math", "searchQuery": "addition, subtraction, multiplication, division, shapes, time" },
        { "icon": "fa-solid fa-book", "topic": "English", "searchQuery": "reading comprehension, spelling, grammar for kids, sentence building" },
        { "icon": "fa-solid fa-flask", "topic": "Science", "searchQuery": "science projects, STEM activities, basic physics, life cycles" },
        { "icon": "fa-solid fa-music", "topic": "Music", "searchQuery": "learning instruments, singing lessons, famous kids songs" },
        { "icon": "fa-solid fa-laptop", "topic": "Computer", "searchQuery": "basic coding, computer parts for kids, typing lessons" },
        { "icon": "fa-solid fa-palette", "topic": "Art", "searchQuery": "drawing tutorials, painting for kids, creative art projects" },
        { "icon": "fa-solid fa-scissors", "topic": "Craft", "searchQuery": "paper crafts, DIY projects, craft competitions" },
        { "icon": "fa-solid fa-book-open", "topic": "Story", "searchQuery": "moral stories, classic tales, animated stories for kids" },
        { "icon": "fa-solid fa-film", "topic": "Movie", "searchQuery": "educational movies, animated classics, inspiring kids movies" },
        { "icon": "fa-solid fa-rocket", "topic": "Space", "searchQuery": "astronomy for kids, NASA videos, space missions" },
        { "icon": "fa-solid fa-globe", "topic": "Social Science", "searchQuery": "geography for kids, history for kids, cultural diversity" },
        { "icon": "fa-solid fa-microphone", "topic": "Spoken English", "searchQuery": "speaking practice, public speaking for kids, English conversation" },
        { "icon": "fa-solid fa-code", "topic": "Coding", "searchQuery": "basic programming for kids, block coding, game development" },
        { "icon": "fa-solid fa-flag", "topic": "Ye Ethiopia Lijoch", "searchQuery": "Ethiopian kids content, Amharic lessons, Ethiopian history" }
    ],
    "8-10": [
        { "icon": "fa-solid fa-calculator", "topic": "All Videos", "searchQuery": "preschool learning videos, educational videos for kids" },
        { "icon": "fa-solid fa-calculator", "topic": "Math", "searchQuery": "fractions, decimals, percentages, algebra basics, problem-solving" },
        { "icon": "fa-solid fa-book", "topic": "English", "searchQuery": "creative writing, essay writing, grammar rules, vocabulary building" },
        { "icon": "fa-solid fa-flask", "topic": "Science", "searchQuery": "earth science, biology basics, chemistry for kids, physics experiments" },
        { "icon": "fa-solid fa-music", "topic": "Music", "searchQuery": "instrument lessons, music theory for kids, famous composers" },
        { "icon": "fa-solid fa-laptop", "topic": "Computer", "searchQuery": "coding for kids, robotics, basic algorithms" },
        { "icon": "fa-solid fa-palette", "topic": "Art", "searchQuery": "advanced drawing, sculpture for kids, art history basics" },
        { "icon": "fa-solid fa-scissors", "topic": "Craft", "searchQuery": "advanced crafts, sewing for kids, creative DIY projects" },
        { "icon": "fa-solid fa-book-open", "topic": "Story", "searchQuery": "adventure stories, famous books for kids, audio stories" },
        { "icon": "fa-solid fa-film", "topic": "Movie", "searchQuery": "documentaries for kids, inspiring movies, animated series" },
        { "icon": "fa-solid fa-rocket", "topic": "Space", "searchQuery": "space exploration, black holes, the solar system, astronauts" },
        { "icon": "fa-solid fa-globe", "topic": "Social Science", "searchQuery": "world history, cultural studies, geography basics" },
        { "icon": "fa-solid fa-microphone", "topic": "Spoken English", "searchQuery": "debates for kids, advanced speaking, storytelling" },
        { "icon": "fa-solid fa-code", "topic": "Coding", "searchQuery": "game development, web design basics, Python for kids" },
        { "icon": "fa-solid fa-flag", "topic": "Ye Ethiopia Lijoch", "searchQuery": "Ethiopian culture, Ethiopian kids songs, Ethiopian language learning" }
    ],
    "11+": [
        { "icon": "fa-solid fa-calculator", "topic": "All Videos", "searchQuery": "educational videos for teenagers, advanced learning for kids" },
        { "icon": "fa-solid fa-calculator", "topic": "Math", "searchQuery": "algebra, geometry, trigonometry, calculus basics, problem-solving" },
        { "icon": "fa-solid fa-book", "topic": "English", "searchQuery": "essay writing, literature analysis, advanced grammar, creative writing tips" },
        { "icon": "fa-solid fa-flask", "topic": "Science", "searchQuery": "physics concepts, chemistry experiments, biology lessons, STEM activities" },
        { "icon": "fa-solid fa-music", "topic": "Music", "searchQuery": "music composition, advanced instrument lessons, famous composers" },
        { "icon": "fa-solid fa-laptop", "topic": "Computer", "searchQuery": "coding for teens, web development, robotics, app development basics" },
        { "icon": "fa-solid fa-palette", "topic": "Art", "searchQuery": "advanced art techniques, digital art, art history, painting tutorials" },
        { "icon": "fa-solid fa-scissors", "topic": "Craft", "searchQuery": "creative DIY projects, advanced crafts, design ideas for teens" },
        { "icon": "fa-solid fa-book-open", "topic": "Story", "searchQuery": "classic literature, famous novels, storytelling tips, book reviews" },
        { "icon": "fa-solid fa-film", "topic": "Movie", "searchQuery": "documentaries for teens, inspiring movies, educational films" },
        { "icon": "fa-solid fa-rocket", "topic": "Space", "searchQuery": "advanced astronomy, space exploration, black holes, NASA projects" },
        { "icon": "fa-solid fa-globe", "topic": "Social Science", "searchQuery": "world history, geography, political science, cultural studies" },
        { "icon": "fa-solid fa-microphone", "topic": "Spoken English", "searchQuery": "public speaking, debate skills, advanced English conversation" },
        { "icon": "fa-solid fa-code", "topic": "Coding", "searchQuery": "Python for teens, game development, machine learning basics, JavaScript tutorials" },
        { "icon": "fa-solid fa-flag", "topic": "Ye Ethiopia Lijoch", "searchQuery": "Ethiopian history, Ethiopian culture, Amharic language lessons for teens" }
    ]
};
